### ISSUE TITLE
Missing dependency phpdocumentor/reflection-docblock

### ISSUE THREAD

**Issue by lenada** [localheinz/github-pulse#11]
## Steps required to reproduce the problem

1. `$ composer require global localheinz/github-pulse:dev-master`
2. `$ php vendor/localheinz/github-pulse/github-pulse.php` 

## Expected Result

* command list /usage instructions

## Actual Result

 ```
PHP Fatal error:  Uncaught Error: Class 'phpDocumentor\Reflection\DocBlockFactory' not found in ./vendor/symfony/property-info/Extractor/PhpDocExtractor.php:58

Stack trace:
#0 ./vendor/localheinz/github-pulse/github-pulse.php(39): Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor->__construct()
#1 {main}
  thrown in ./vendor/symfony/property-info/Extractor/PhpDocExtractor.php on line 58
```

requiring `phpdocumentor/reflection-docblock` seems to help

@localheinz should `phpdocumentor/reflection-docblock` be explicitly defined as a dependency?

**Comment by localheinz** [comment]
@lenada 

Reproduced the error by running

```
$ git clone git@github.com:localheinz/github-pulse.git
$ cd github-pulse
$ composer install --no-dev
$ ./github-pulse
```

Taking a look!
