### ISSUE TITLE
Feature request: Add support for creating pulse for user (maybe group of users), not only for orgs

### ISSUE THREAD

**Issue by keradus** [localheinz/github-pulse#37]
WDYT?

**Comment by localheinz** [comment]
Sounds good, need to put some work into it!

**Comment by keradus** [comment]
then, repo/group of repos ?

could be done 2 ways.

- gather initial data for organization, then filter repos, gather data about filtered repos, filtetr users
- call for stats of user instead of organization first. probably way different flow here
