### ISSUE TITLE
Support for Github Enterprise organizations?

### ISSUE THREAD

**Issue by dnoliver** [localheinz/github-pulse#39]
## Steps required to reproduce the problem

1. You need to have an Enterprise Github instance (?)
2.  execute `github-pulse generate org-name`

## Expected Result

* `github-pulse` will find the org, and do it job

## Actual Result

* `github-pulse` cannot find the org
* Possible because of it is using Github Client
* https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Client.php#L131
* api.github.com is harcoded there :(

Maybe something like `github-pulse generate --github-api=https://api.enterprise.github.instance <org name>`

But I think it depends on how much customization you can apply to the github client

Very interesting project @localheinz!

**Comment by localheinz** [comment]
Thank you for your feedback, @dnoliver!

Let me take a look at this as soon as I have some time. Glad you like it!
